/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as Error503RouteImport } from './routes/error/503'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignOutRouteImport } from './routes/auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthChangePasswordRouteImport } from './routes/auth/change-password'
import { Route as AppErrorRouteRouteImport } from './routes/app/error/route'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as AppSubmissionsIndexRouteImport } from './routes/app/submissions/index'
import { Route as AppRoomsIndexRouteImport } from './routes/app/rooms/index'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppErrorIndexRouteImport } from './routes/app/error/index'
import { Route as AppSubmissionsSubmissionIdRouteImport } from './routes/app/submissions/$submissionId'
import { Route as AppRoomsCreateRouteImport } from './routes/app/rooms/create'
import { Route as AppErrorGoneRouteImport } from './routes/app/error/gone'
import { Route as AppError404RouteImport } from './routes/app/error/404'
import { Route as AppError403RouteImport } from './routes/app/error/403'
import { Route as AppRoomsRoomIdRouteRouteImport } from './routes/app/rooms/$roomId/route'
import { Route as AppProblemsProblemIdRouteRouteImport } from './routes/app/problems/$problemId/route'
import { Route as AppContestsContestIdRouteRouteImport } from './routes/app/contests/$contestId/route'
import { Route as AppRoomsRoomIdIndexRouteImport } from './routes/app/rooms/$roomId/index'
import { Route as AppProblemsProblemIdIndexRouteImport } from './routes/app/problems/$problemId/index'
import { Route as AppContestsContestIdIndexRouteImport } from './routes/app/contests/$contestId/index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/app/admin/users/index'
import { Route as AppRoomsRoomIdSubmissionsRouteImport } from './routes/app/rooms/$roomId/submissions'
import { Route as AppRoomsRoomIdMembersRouteImport } from './routes/app/rooms/$roomId/members'
import { Route as AppRoomsRoomIdEditRouteImport } from './routes/app/rooms/$roomId/edit'
import { Route as AppProblemsProblemIdTestcasesRouteImport } from './routes/app/problems/$problemId/testcases'
import { Route as AppProblemsProblemIdEditRouteImport } from './routes/app/problems/$problemId/edit'
import { Route as AppContestsContestIdProblemsRouteImport } from './routes/app/contests/$contestId/problems'
import { Route as AppContestsContestIdLeaderboardRouteImport } from './routes/app/contests/$contestId/leaderboard'
import { Route as AppContestsContestIdEditRouteImport } from './routes/app/contests/$contestId/edit'
import { Route as AppAdminUsersUserIdRouteImport } from './routes/app/admin/users/$userId'
import { Route as AppRoomsRoomIdProblemsIndexRouteImport } from './routes/app/rooms/$roomId/problems/index'
import { Route as AppRoomsRoomIdContestsIndexRouteImport } from './routes/app/rooms/$roomId/contests/index'
import { Route as AppRoomsRoomIdProblemsCreateRouteImport } from './routes/app/rooms/$roomId/problems/create'
import { Route as AppRoomsRoomIdContestsCreateRouteImport } from './routes/app/rooms/$roomId/contests/create'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const Error503Route = Error503RouteImport.update({
  id: '/error/503',
  path: '/error/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppErrorRouteRoute = AppErrorRouteRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubmissionsIndexRoute = AppSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRoomsIndexRoute = AppRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppErrorIndexRoute = AppErrorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppErrorRouteRoute,
} as any)
const AppSubmissionsSubmissionIdRoute =
  AppSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppRoomsCreateRoute = AppRoomsCreateRouteImport.update({
  id: '/rooms/create',
  path: '/rooms/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppErrorGoneRoute = AppErrorGoneRouteImport.update({
  id: '/gone',
  path: '/gone',
  getParentRoute: () => AppErrorRouteRoute,
} as any)
const AppError404Route = AppError404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => AppErrorRouteRoute,
} as any)
const AppError403Route = AppError403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => AppErrorRouteRoute,
} as any)
const AppRoomsRoomIdRouteRoute = AppRoomsRoomIdRouteRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProblemsProblemIdRouteRoute =
  AppProblemsProblemIdRouteRouteImport.update({
    id: '/problems/$problemId',
    path: '/problems/$problemId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppContestsContestIdRouteRoute =
  AppContestsContestIdRouteRouteImport.update({
    id: '/contests/$contestId',
    path: '/contests/$contestId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppRoomsRoomIdIndexRoute = AppRoomsRoomIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoomsRoomIdRouteRoute,
} as any)
const AppProblemsProblemIdIndexRoute =
  AppProblemsProblemIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProblemsProblemIdRouteRoute,
  } as any)
const AppContestsContestIdIndexRoute =
  AppContestsContestIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppContestsContestIdRouteRoute,
  } as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppRoomsRoomIdSubmissionsRoute =
  AppRoomsRoomIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AppRoomsRoomIdRouteRoute,
  } as any)
const AppRoomsRoomIdMembersRoute = AppRoomsRoomIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoomsRoomIdRouteRoute,
} as any)
const AppRoomsRoomIdEditRoute = AppRoomsRoomIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppRoomsRoomIdRouteRoute,
} as any)
const AppProblemsProblemIdTestcasesRoute =
  AppProblemsProblemIdTestcasesRouteImport.update({
    id: '/testcases',
    path: '/testcases',
    getParentRoute: () => AppProblemsProblemIdRouteRoute,
  } as any)
const AppProblemsProblemIdEditRoute =
  AppProblemsProblemIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppProblemsProblemIdRouteRoute,
  } as any)
const AppContestsContestIdProblemsRoute =
  AppContestsContestIdProblemsRouteImport.update({
    id: '/problems',
    path: '/problems',
    getParentRoute: () => AppContestsContestIdRouteRoute,
  } as any)
const AppContestsContestIdLeaderboardRoute =
  AppContestsContestIdLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AppContestsContestIdRouteRoute,
  } as any)
const AppContestsContestIdEditRoute =
  AppContestsContestIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppContestsContestIdRouteRoute,
  } as any)
const AppAdminUsersUserIdRoute = AppAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppRoomsRoomIdProblemsIndexRoute =
  AppRoomsRoomIdProblemsIndexRouteImport.update({
    id: '/problems/',
    path: '/problems/',
    getParentRoute: () => AppRoomsRoomIdRouteRoute,
  } as any)
const AppRoomsRoomIdContestsIndexRoute =
  AppRoomsRoomIdContestsIndexRouteImport.update({
    id: '/contests/',
    path: '/contests/',
    getParentRoute: () => AppRoomsRoomIdRouteRoute,
  } as any)
const AppRoomsRoomIdProblemsCreateRoute =
  AppRoomsRoomIdProblemsCreateRouteImport.update({
    id: '/problems/create',
    path: '/problems/create',
    getParentRoute: () => AppRoomsRoomIdRouteRoute,
  } as any)
const AppRoomsRoomIdContestsCreateRoute =
  AppRoomsRoomIdContestsCreateRouteImport.update({
    id: '/contests/create',
    path: '/contests/create',
    getParentRoute: () => AppRoomsRoomIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/error': typeof AppErrorRouteRouteWithChildren
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/error/503': typeof Error503Route
  '/app/': typeof AppIndexRoute
  '/app/contests/$contestId': typeof AppContestsContestIdRouteRouteWithChildren
  '/app/problems/$problemId': typeof AppProblemsProblemIdRouteRouteWithChildren
  '/app/rooms/$roomId': typeof AppRoomsRoomIdRouteRouteWithChildren
  '/app/error/403': typeof AppError403Route
  '/app/error/404': typeof AppError404Route
  '/app/error/gone': typeof AppErrorGoneRoute
  '/app/rooms/create': typeof AppRoomsCreateRoute
  '/app/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
  '/app/error/': typeof AppErrorIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/rooms': typeof AppRoomsIndexRoute
  '/app/submissions': typeof AppSubmissionsIndexRoute
  '/app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/app/contests/$contestId/edit': typeof AppContestsContestIdEditRoute
  '/app/contests/$contestId/leaderboard': typeof AppContestsContestIdLeaderboardRoute
  '/app/contests/$contestId/problems': typeof AppContestsContestIdProblemsRoute
  '/app/problems/$problemId/edit': typeof AppProblemsProblemIdEditRoute
  '/app/problems/$problemId/testcases': typeof AppProblemsProblemIdTestcasesRoute
  '/app/rooms/$roomId/edit': typeof AppRoomsRoomIdEditRoute
  '/app/rooms/$roomId/members': typeof AppRoomsRoomIdMembersRoute
  '/app/rooms/$roomId/submissions': typeof AppRoomsRoomIdSubmissionsRoute
  '/app/admin/users': typeof AppAdminUsersIndexRoute
  '/app/contests/$contestId/': typeof AppContestsContestIdIndexRoute
  '/app/problems/$problemId/': typeof AppProblemsProblemIdIndexRoute
  '/app/rooms/$roomId/': typeof AppRoomsRoomIdIndexRoute
  '/app/rooms/$roomId/contests/create': typeof AppRoomsRoomIdContestsCreateRoute
  '/app/rooms/$roomId/problems/create': typeof AppRoomsRoomIdProblemsCreateRoute
  '/app/rooms/$roomId/contests': typeof AppRoomsRoomIdContestsIndexRoute
  '/app/rooms/$roomId/problems': typeof AppRoomsRoomIdProblemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/error/503': typeof Error503Route
  '/app': typeof AppIndexRoute
  '/app/error/403': typeof AppError403Route
  '/app/error/404': typeof AppError404Route
  '/app/error/gone': typeof AppErrorGoneRoute
  '/app/rooms/create': typeof AppRoomsCreateRoute
  '/app/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
  '/app/error': typeof AppErrorIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/rooms': typeof AppRoomsIndexRoute
  '/app/submissions': typeof AppSubmissionsIndexRoute
  '/app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/app/contests/$contestId/edit': typeof AppContestsContestIdEditRoute
  '/app/contests/$contestId/leaderboard': typeof AppContestsContestIdLeaderboardRoute
  '/app/contests/$contestId/problems': typeof AppContestsContestIdProblemsRoute
  '/app/problems/$problemId/edit': typeof AppProblemsProblemIdEditRoute
  '/app/problems/$problemId/testcases': typeof AppProblemsProblemIdTestcasesRoute
  '/app/rooms/$roomId/edit': typeof AppRoomsRoomIdEditRoute
  '/app/rooms/$roomId/members': typeof AppRoomsRoomIdMembersRoute
  '/app/rooms/$roomId/submissions': typeof AppRoomsRoomIdSubmissionsRoute
  '/app/admin/users': typeof AppAdminUsersIndexRoute
  '/app/contests/$contestId': typeof AppContestsContestIdIndexRoute
  '/app/problems/$problemId': typeof AppProblemsProblemIdIndexRoute
  '/app/rooms/$roomId': typeof AppRoomsRoomIdIndexRoute
  '/app/rooms/$roomId/contests/create': typeof AppRoomsRoomIdContestsCreateRoute
  '/app/rooms/$roomId/problems/create': typeof AppRoomsRoomIdProblemsCreateRoute
  '/app/rooms/$roomId/contests': typeof AppRoomsRoomIdContestsIndexRoute
  '/app/rooms/$roomId/problems': typeof AppRoomsRoomIdProblemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/error': typeof AppErrorRouteRouteWithChildren
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/error/503': typeof Error503Route
  '/app/': typeof AppIndexRoute
  '/app/contests/$contestId': typeof AppContestsContestIdRouteRouteWithChildren
  '/app/problems/$problemId': typeof AppProblemsProblemIdRouteRouteWithChildren
  '/app/rooms/$roomId': typeof AppRoomsRoomIdRouteRouteWithChildren
  '/app/error/403': typeof AppError403Route
  '/app/error/404': typeof AppError404Route
  '/app/error/gone': typeof AppErrorGoneRoute
  '/app/rooms/create': typeof AppRoomsCreateRoute
  '/app/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
  '/app/error/': typeof AppErrorIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/rooms/': typeof AppRoomsIndexRoute
  '/app/submissions/': typeof AppSubmissionsIndexRoute
  '/app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/app/contests/$contestId/edit': typeof AppContestsContestIdEditRoute
  '/app/contests/$contestId/leaderboard': typeof AppContestsContestIdLeaderboardRoute
  '/app/contests/$contestId/problems': typeof AppContestsContestIdProblemsRoute
  '/app/problems/$problemId/edit': typeof AppProblemsProblemIdEditRoute
  '/app/problems/$problemId/testcases': typeof AppProblemsProblemIdTestcasesRoute
  '/app/rooms/$roomId/edit': typeof AppRoomsRoomIdEditRoute
  '/app/rooms/$roomId/members': typeof AppRoomsRoomIdMembersRoute
  '/app/rooms/$roomId/submissions': typeof AppRoomsRoomIdSubmissionsRoute
  '/app/admin/users/': typeof AppAdminUsersIndexRoute
  '/app/contests/$contestId/': typeof AppContestsContestIdIndexRoute
  '/app/problems/$problemId/': typeof AppProblemsProblemIdIndexRoute
  '/app/rooms/$roomId/': typeof AppRoomsRoomIdIndexRoute
  '/app/rooms/$roomId/contests/create': typeof AppRoomsRoomIdContestsCreateRoute
  '/app/rooms/$roomId/problems/create': typeof AppRoomsRoomIdProblemsCreateRoute
  '/app/rooms/$roomId/contests/': typeof AppRoomsRoomIdContestsIndexRoute
  '/app/rooms/$roomId/problems/': typeof AppRoomsRoomIdProblemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/error'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/error/503'
    | '/app/'
    | '/app/contests/$contestId'
    | '/app/problems/$problemId'
    | '/app/rooms/$roomId'
    | '/app/error/403'
    | '/app/error/404'
    | '/app/error/gone'
    | '/app/rooms/create'
    | '/app/submissions/$submissionId'
    | '/app/error/'
    | '/app/profile'
    | '/app/rooms'
    | '/app/submissions'
    | '/app/admin/users/$userId'
    | '/app/contests/$contestId/edit'
    | '/app/contests/$contestId/leaderboard'
    | '/app/contests/$contestId/problems'
    | '/app/problems/$problemId/edit'
    | '/app/problems/$problemId/testcases'
    | '/app/rooms/$roomId/edit'
    | '/app/rooms/$roomId/members'
    | '/app/rooms/$roomId/submissions'
    | '/app/admin/users'
    | '/app/contests/$contestId/'
    | '/app/problems/$problemId/'
    | '/app/rooms/$roomId/'
    | '/app/rooms/$roomId/contests/create'
    | '/app/rooms/$roomId/problems/create'
    | '/app/rooms/$roomId/contests'
    | '/app/rooms/$roomId/problems'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/admin'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/error/503'
    | '/app'
    | '/app/error/403'
    | '/app/error/404'
    | '/app/error/gone'
    | '/app/rooms/create'
    | '/app/submissions/$submissionId'
    | '/app/error'
    | '/app/profile'
    | '/app/rooms'
    | '/app/submissions'
    | '/app/admin/users/$userId'
    | '/app/contests/$contestId/edit'
    | '/app/contests/$contestId/leaderboard'
    | '/app/contests/$contestId/problems'
    | '/app/problems/$problemId/edit'
    | '/app/problems/$problemId/testcases'
    | '/app/rooms/$roomId/edit'
    | '/app/rooms/$roomId/members'
    | '/app/rooms/$roomId/submissions'
    | '/app/admin/users'
    | '/app/contests/$contestId'
    | '/app/problems/$problemId'
    | '/app/rooms/$roomId'
    | '/app/rooms/$roomId/contests/create'
    | '/app/rooms/$roomId/problems/create'
    | '/app/rooms/$roomId/contests'
    | '/app/rooms/$roomId/problems'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/error'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/error/503'
    | '/app/'
    | '/app/contests/$contestId'
    | '/app/problems/$problemId'
    | '/app/rooms/$roomId'
    | '/app/error/403'
    | '/app/error/404'
    | '/app/error/gone'
    | '/app/rooms/create'
    | '/app/submissions/$submissionId'
    | '/app/error/'
    | '/app/profile/'
    | '/app/rooms/'
    | '/app/submissions/'
    | '/app/admin/users/$userId'
    | '/app/contests/$contestId/edit'
    | '/app/contests/$contestId/leaderboard'
    | '/app/contests/$contestId/problems'
    | '/app/problems/$problemId/edit'
    | '/app/problems/$problemId/testcases'
    | '/app/rooms/$roomId/edit'
    | '/app/rooms/$roomId/members'
    | '/app/rooms/$roomId/submissions'
    | '/app/admin/users/'
    | '/app/contests/$contestId/'
    | '/app/problems/$problemId/'
    | '/app/rooms/$roomId/'
    | '/app/rooms/$roomId/contests/create'
    | '/app/rooms/$roomId/problems/create'
    | '/app/rooms/$roomId/contests/'
    | '/app/rooms/$roomId/problems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  Error503Route: typeof Error503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/error/503': {
      id: '/error/503'
      path: '/error/503'
      fullPath: '/error/503'
      preLoaderRoute: typeof Error503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-out': {
      id: '/auth/sign-out'
      path: '/sign-out'
      fullPath: '/auth/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/error': {
      id: '/app/error'
      path: '/error'
      fullPath: '/app/error'
      preLoaderRoute: typeof AppErrorRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/submissions/': {
      id: '/app/submissions/'
      path: '/submissions'
      fullPath: '/app/submissions'
      preLoaderRoute: typeof AppSubmissionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rooms/': {
      id: '/app/rooms/'
      path: '/rooms'
      fullPath: '/app/rooms'
      preLoaderRoute: typeof AppRoomsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/error/': {
      id: '/app/error/'
      path: '/'
      fullPath: '/app/error/'
      preLoaderRoute: typeof AppErrorIndexRouteImport
      parentRoute: typeof AppErrorRouteRoute
    }
    '/app/submissions/$submissionId': {
      id: '/app/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/app/submissions/$submissionId'
      preLoaderRoute: typeof AppSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rooms/create': {
      id: '/app/rooms/create'
      path: '/rooms/create'
      fullPath: '/app/rooms/create'
      preLoaderRoute: typeof AppRoomsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/error/gone': {
      id: '/app/error/gone'
      path: '/gone'
      fullPath: '/app/error/gone'
      preLoaderRoute: typeof AppErrorGoneRouteImport
      parentRoute: typeof AppErrorRouteRoute
    }
    '/app/error/404': {
      id: '/app/error/404'
      path: '/404'
      fullPath: '/app/error/404'
      preLoaderRoute: typeof AppError404RouteImport
      parentRoute: typeof AppErrorRouteRoute
    }
    '/app/error/403': {
      id: '/app/error/403'
      path: '/403'
      fullPath: '/app/error/403'
      preLoaderRoute: typeof AppError403RouteImport
      parentRoute: typeof AppErrorRouteRoute
    }
    '/app/rooms/$roomId': {
      id: '/app/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/app/rooms/$roomId'
      preLoaderRoute: typeof AppRoomsRoomIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/problems/$problemId': {
      id: '/app/problems/$problemId'
      path: '/problems/$problemId'
      fullPath: '/app/problems/$problemId'
      preLoaderRoute: typeof AppProblemsProblemIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/contests/$contestId': {
      id: '/app/contests/$contestId'
      path: '/contests/$contestId'
      fullPath: '/app/contests/$contestId'
      preLoaderRoute: typeof AppContestsContestIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rooms/$roomId/': {
      id: '/app/rooms/$roomId/'
      path: '/'
      fullPath: '/app/rooms/$roomId/'
      preLoaderRoute: typeof AppRoomsRoomIdIndexRouteImport
      parentRoute: typeof AppRoomsRoomIdRouteRoute
    }
    '/app/problems/$problemId/': {
      id: '/app/problems/$problemId/'
      path: '/'
      fullPath: '/app/problems/$problemId/'
      preLoaderRoute: typeof AppProblemsProblemIdIndexRouteImport
      parentRoute: typeof AppProblemsProblemIdRouteRoute
    }
    '/app/contests/$contestId/': {
      id: '/app/contests/$contestId/'
      path: '/'
      fullPath: '/app/contests/$contestId/'
      preLoaderRoute: typeof AppContestsContestIdIndexRouteImport
      parentRoute: typeof AppContestsContestIdRouteRoute
    }
    '/app/admin/users/': {
      id: '/app/admin/users/'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/rooms/$roomId/submissions': {
      id: '/app/rooms/$roomId/submissions'
      path: '/submissions'
      fullPath: '/app/rooms/$roomId/submissions'
      preLoaderRoute: typeof AppRoomsRoomIdSubmissionsRouteImport
      parentRoute: typeof AppRoomsRoomIdRouteRoute
    }
    '/app/rooms/$roomId/members': {
      id: '/app/rooms/$roomId/members'
      path: '/members'
      fullPath: '/app/rooms/$roomId/members'
      preLoaderRoute: typeof AppRoomsRoomIdMembersRouteImport
      parentRoute: typeof AppRoomsRoomIdRouteRoute
    }
    '/app/rooms/$roomId/edit': {
      id: '/app/rooms/$roomId/edit'
      path: '/edit'
      fullPath: '/app/rooms/$roomId/edit'
      preLoaderRoute: typeof AppRoomsRoomIdEditRouteImport
      parentRoute: typeof AppRoomsRoomIdRouteRoute
    }
    '/app/problems/$problemId/testcases': {
      id: '/app/problems/$problemId/testcases'
      path: '/testcases'
      fullPath: '/app/problems/$problemId/testcases'
      preLoaderRoute: typeof AppProblemsProblemIdTestcasesRouteImport
      parentRoute: typeof AppProblemsProblemIdRouteRoute
    }
    '/app/problems/$problemId/edit': {
      id: '/app/problems/$problemId/edit'
      path: '/edit'
      fullPath: '/app/problems/$problemId/edit'
      preLoaderRoute: typeof AppProblemsProblemIdEditRouteImport
      parentRoute: typeof AppProblemsProblemIdRouteRoute
    }
    '/app/contests/$contestId/problems': {
      id: '/app/contests/$contestId/problems'
      path: '/problems'
      fullPath: '/app/contests/$contestId/problems'
      preLoaderRoute: typeof AppContestsContestIdProblemsRouteImport
      parentRoute: typeof AppContestsContestIdRouteRoute
    }
    '/app/contests/$contestId/leaderboard': {
      id: '/app/contests/$contestId/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/contests/$contestId/leaderboard'
      preLoaderRoute: typeof AppContestsContestIdLeaderboardRouteImport
      parentRoute: typeof AppContestsContestIdRouteRoute
    }
    '/app/contests/$contestId/edit': {
      id: '/app/contests/$contestId/edit'
      path: '/edit'
      fullPath: '/app/contests/$contestId/edit'
      preLoaderRoute: typeof AppContestsContestIdEditRouteImport
      parentRoute: typeof AppContestsContestIdRouteRoute
    }
    '/app/admin/users/$userId': {
      id: '/app/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/app/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/rooms/$roomId/problems/': {
      id: '/app/rooms/$roomId/problems/'
      path: '/problems'
      fullPath: '/app/rooms/$roomId/problems'
      preLoaderRoute: typeof AppRoomsRoomIdProblemsIndexRouteImport
      parentRoute: typeof AppRoomsRoomIdRouteRoute
    }
    '/app/rooms/$roomId/contests/': {
      id: '/app/rooms/$roomId/contests/'
      path: '/contests'
      fullPath: '/app/rooms/$roomId/contests'
      preLoaderRoute: typeof AppRoomsRoomIdContestsIndexRouteImport
      parentRoute: typeof AppRoomsRoomIdRouteRoute
    }
    '/app/rooms/$roomId/problems/create': {
      id: '/app/rooms/$roomId/problems/create'
      path: '/problems/create'
      fullPath: '/app/rooms/$roomId/problems/create'
      preLoaderRoute: typeof AppRoomsRoomIdProblemsCreateRouteImport
      parentRoute: typeof AppRoomsRoomIdRouteRoute
    }
    '/app/rooms/$roomId/contests/create': {
      id: '/app/rooms/$roomId/contests/create'
      path: '/contests/create'
      fullPath: '/app/rooms/$roomId/contests/create'
      preLoaderRoute: typeof AppRoomsRoomIdContestsCreateRouteImport
      parentRoute: typeof AppRoomsRoomIdRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminUsersUserIdRoute: typeof AppAdminUsersUserIdRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminUsersUserIdRoute: AppAdminUsersUserIdRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppErrorRouteRouteChildren {
  AppError403Route: typeof AppError403Route
  AppError404Route: typeof AppError404Route
  AppErrorGoneRoute: typeof AppErrorGoneRoute
  AppErrorIndexRoute: typeof AppErrorIndexRoute
}

const AppErrorRouteRouteChildren: AppErrorRouteRouteChildren = {
  AppError403Route: AppError403Route,
  AppError404Route: AppError404Route,
  AppErrorGoneRoute: AppErrorGoneRoute,
  AppErrorIndexRoute: AppErrorIndexRoute,
}

const AppErrorRouteRouteWithChildren = AppErrorRouteRoute._addFileChildren(
  AppErrorRouteRouteChildren,
)

interface AppContestsContestIdRouteRouteChildren {
  AppContestsContestIdEditRoute: typeof AppContestsContestIdEditRoute
  AppContestsContestIdLeaderboardRoute: typeof AppContestsContestIdLeaderboardRoute
  AppContestsContestIdProblemsRoute: typeof AppContestsContestIdProblemsRoute
  AppContestsContestIdIndexRoute: typeof AppContestsContestIdIndexRoute
}

const AppContestsContestIdRouteRouteChildren: AppContestsContestIdRouteRouteChildren =
  {
    AppContestsContestIdEditRoute: AppContestsContestIdEditRoute,
    AppContestsContestIdLeaderboardRoute: AppContestsContestIdLeaderboardRoute,
    AppContestsContestIdProblemsRoute: AppContestsContestIdProblemsRoute,
    AppContestsContestIdIndexRoute: AppContestsContestIdIndexRoute,
  }

const AppContestsContestIdRouteRouteWithChildren =
  AppContestsContestIdRouteRoute._addFileChildren(
    AppContestsContestIdRouteRouteChildren,
  )

interface AppProblemsProblemIdRouteRouteChildren {
  AppProblemsProblemIdEditRoute: typeof AppProblemsProblemIdEditRoute
  AppProblemsProblemIdTestcasesRoute: typeof AppProblemsProblemIdTestcasesRoute
  AppProblemsProblemIdIndexRoute: typeof AppProblemsProblemIdIndexRoute
}

const AppProblemsProblemIdRouteRouteChildren: AppProblemsProblemIdRouteRouteChildren =
  {
    AppProblemsProblemIdEditRoute: AppProblemsProblemIdEditRoute,
    AppProblemsProblemIdTestcasesRoute: AppProblemsProblemIdTestcasesRoute,
    AppProblemsProblemIdIndexRoute: AppProblemsProblemIdIndexRoute,
  }

const AppProblemsProblemIdRouteRouteWithChildren =
  AppProblemsProblemIdRouteRoute._addFileChildren(
    AppProblemsProblemIdRouteRouteChildren,
  )

interface AppRoomsRoomIdRouteRouteChildren {
  AppRoomsRoomIdEditRoute: typeof AppRoomsRoomIdEditRoute
  AppRoomsRoomIdMembersRoute: typeof AppRoomsRoomIdMembersRoute
  AppRoomsRoomIdSubmissionsRoute: typeof AppRoomsRoomIdSubmissionsRoute
  AppRoomsRoomIdIndexRoute: typeof AppRoomsRoomIdIndexRoute
  AppRoomsRoomIdContestsCreateRoute: typeof AppRoomsRoomIdContestsCreateRoute
  AppRoomsRoomIdProblemsCreateRoute: typeof AppRoomsRoomIdProblemsCreateRoute
  AppRoomsRoomIdContestsIndexRoute: typeof AppRoomsRoomIdContestsIndexRoute
  AppRoomsRoomIdProblemsIndexRoute: typeof AppRoomsRoomIdProblemsIndexRoute
}

const AppRoomsRoomIdRouteRouteChildren: AppRoomsRoomIdRouteRouteChildren = {
  AppRoomsRoomIdEditRoute: AppRoomsRoomIdEditRoute,
  AppRoomsRoomIdMembersRoute: AppRoomsRoomIdMembersRoute,
  AppRoomsRoomIdSubmissionsRoute: AppRoomsRoomIdSubmissionsRoute,
  AppRoomsRoomIdIndexRoute: AppRoomsRoomIdIndexRoute,
  AppRoomsRoomIdContestsCreateRoute: AppRoomsRoomIdContestsCreateRoute,
  AppRoomsRoomIdProblemsCreateRoute: AppRoomsRoomIdProblemsCreateRoute,
  AppRoomsRoomIdContestsIndexRoute: AppRoomsRoomIdContestsIndexRoute,
  AppRoomsRoomIdProblemsIndexRoute: AppRoomsRoomIdProblemsIndexRoute,
}

const AppRoomsRoomIdRouteRouteWithChildren =
  AppRoomsRoomIdRouteRoute._addFileChildren(AppRoomsRoomIdRouteRouteChildren)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppErrorRouteRoute: typeof AppErrorRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppContestsContestIdRouteRoute: typeof AppContestsContestIdRouteRouteWithChildren
  AppProblemsProblemIdRouteRoute: typeof AppProblemsProblemIdRouteRouteWithChildren
  AppRoomsRoomIdRouteRoute: typeof AppRoomsRoomIdRouteRouteWithChildren
  AppRoomsCreateRoute: typeof AppRoomsCreateRoute
  AppSubmissionsSubmissionIdRoute: typeof AppSubmissionsSubmissionIdRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppRoomsIndexRoute: typeof AppRoomsIndexRoute
  AppSubmissionsIndexRoute: typeof AppSubmissionsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppErrorRouteRoute: AppErrorRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppContestsContestIdRouteRoute: AppContestsContestIdRouteRouteWithChildren,
  AppProblemsProblemIdRouteRoute: AppProblemsProblemIdRouteRouteWithChildren,
  AppRoomsRoomIdRouteRoute: AppRoomsRoomIdRouteRouteWithChildren,
  AppRoomsCreateRoute: AppRoomsCreateRoute,
  AppSubmissionsSubmissionIdRoute: AppSubmissionsSubmissionIdRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppRoomsIndexRoute: AppRoomsIndexRoute,
  AppSubmissionsIndexRoute: AppSubmissionsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  Error503Route: Error503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
